package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.ResponseBody;

import org.springframework.web.bind.annotation.CrossOrigin;

@Controller    // This means that this class is a Controller
@RequestMapping(path = "/entities.mail") // This means URL's start with /demo (after Application path)
public class MainController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private MailRepository mailRepository;

    @CrossOrigin(origins = "https://localhost:3000")
    @RequestMapping(method = RequestMethod.POST) // Map ONLY GET Requests
    public @ResponseBody
    String addNewMail(@RequestBody Mail input) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        input.getAttachmentsList().stream().forEach((att) -> {
            att.setMail(input);
        });
        mailRepository.save(input);
        return "Saved";
    }

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<Mail> getAllMail() {
        // This returns a JSON or XML with the users
        return mailRepository.findAll();
    }
}
